### ISSUE TITLE
Running `php please site:clear` followed by `php please migrate:site` results in error

### ISSUE THREAD

**Issue by sluther** [statamic/migrator#23] opened 2019-12-15 05:46 UTC
When migrating the v2 demo content, running `php please site:clear` followed by `php please migrate:site` results in the following error:

```
Facade\Ignition\Exceptions\ViewException
Object of class Statamic\Fields\Value could not be converted to int
```

As mentioned in my previous ticket, I know that v3 doesn't have any demo content, but since I'm following the steps in the migration guide, I think this is a bug.

**Comment by jasonvarga** [comment] 2019-12-15 14:07
Where do you see that error? When running the command? When visiting a url?

**Comment by sluther** [comment] 2019-12-15 14:33
Hi Jason,

My bad on not being more specific. Yes, the error shows when visiting the site in the browser.

I got around the error by not clearing my site prior to migrating the v2 demo content.

**Comment by jesseleite** [comment] 2019-12-16 01:27
Not sure how to reproduce this.  Maybe we can get a copy of your `site` folder?

**Comment by sluther** [comment] 2019-12-16 05:04
I've attached my v2 site folder (zipped). Hopefully this helps!

[site.zip](https://github.com/statamic/migrator/files/3966141/site.zip)

**Comment by jasonvarga** [comment] 2019-12-16 14:20
It looks like you've just zipped the folder, but nothing inside it :)

**Comment by jasonvarga** [comment] 2019-12-16 14:22
Anyway:

> Yes, the error shows when visiting the site in the browser.

What URL though? The home page? Then just show the home page template, content markdown file, and blueprint.

**Comment by sluther** [comment] 2019-12-16 15:45
Hi Jason,

Here's my site folder again. This time, it's not an empty folder... Sorry about that!

[site.zip](https://github.com/statamic/migrator/files/3968817/site.zip)

**Comment by jesseleite** [comment] 2019-12-16 20:11
Can you let us know which URL you are hitting in browser, and paste the full error stack trace?

**Comment by sluther** [comment] 2019-12-16 22:19
I'm hitting the following URL in my browser:
http://sandbox.localhost/

Here's the full stacktrace:
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Object of class...', '/var/www/vendor...', 988, Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php(988): array_slice(Array, 0, Object(Statamic\Fields\Value), true)
#2 /var/www/vendor/statamic/cms/src/Stache/Query/Builder.php(45): Illuminate\Support\Collection->slice(0, Object(Statamic\Fields\Value))
#3 /var/www/vendor/statamic/cms/src/Stache/Query/Builder.php(29): Statamic\Stache\Query\Builder->limitKeys(Object(Statamic\Data\DataCollection))
#4 /var/www/vendor/statamic/cms/src/Tags/Query/GetsResults.php(25): Statamic\Stache\Query\Builder->get()
#5 /var/www/vendor/statamic/cms/src/Tags/Collection/Entries.php(44): Statamic\Tags\Collection\Entries->results(Object(Statamic\Stache\Query\EntryQueryBuilder))
#6 /var/www/vendor/statamic/cms/src/Tags/Collection/Collection.php(32): Statamic\Tags\Collection\Entries->get()
#7 /var/www/vendor/statamic/cms/src/Tags/Collection/Collection.php(24): Statamic\Tags\Collection\Collection->index()
#8 [internal function]: Statamic\Tags\Collection\Collection->__call('blog', Array)
#9 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(151): call_user_func(Array)
#10 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'collection', Array, '\n\t\t\t{{ partial:...', Array)
#11 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(579): call_user_func_array(Array, Array)
#12 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(173): Statamic\View\Antlers\Parser->parseCallbackTags('<section class=...', Array)
#13 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(126): Statamic\View\Antlers\Parser->parse('<section class=...', Array)
#14 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(88): Statamic\View\Antlers\Parser->parseView('/var/www/resour...', '<section class=...', Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get('/var/www/resour...', Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#17 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#18 /var/www/vendor/statamic/cms/src/View/View.php(74): Illuminate\View\View->render()
#19 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(139): Statamic\View\View->render()
#20 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(44): Statamic\Http\Responses\DataResponse->contents()
#21 /var/www/vendor/statamic/cms/src/Entries/Entry.php(278): Statamic\Http\Responses\DataResponse->toResponse(Object(Illuminate\Http\Request))
#22 /var/www/vendor/statamic/cms/src/Structures/Page.php(281): Statamic\Entries\Entry->toResponse(Object(Illuminate\Http\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(734): Statamic\Structures\Page->toResponse(Object(Illuminate\Http\Request))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(177): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\VanityRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PermanentRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}
Object of class Statamic\Fields\Value could not be converted to int
/var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php#988
ErrorException
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Object of class...', '/var/www/vendor...', 988, Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Support/Collection.php(988): array_slice(Array, 0, Object(Statamic\Fields\Value), true)
#2 /var/www/vendor/statamic/cms/src/Stache/Query/Builder.php(45): Illuminate\Support\Collection->slice(0, Object(Statamic\Fields\Value))
#3 /var/www/vendor/statamic/cms/src/Stache/Query/Builder.php(29): Statamic\Stache\Query\Builder->limitKeys(Object(Statamic\Data\DataCollection))
#4 /var/www/vendor/statamic/cms/src/Tags/Query/GetsResults.php(25): Statamic\Stache\Query\Builder->get()
#5 /var/www/vendor/statamic/cms/src/Tags/Collection/Entries.php(44): Statamic\Tags\Collection\Entries->results(Object(Statamic\Stache\Query\EntryQueryBuilder))
#6 /var/www/vendor/statamic/cms/src/Tags/Collection/Collection.php(32): Statamic\Tags\Collection\Entries->get()
#7 /var/www/vendor/statamic/cms/src/Tags/Collection/Collection.php(24): Statamic\Tags\Collection\Collection->index()
#8 [internal function]: Statamic\Tags\Collection\Collection->__call('blog', Array)
#9 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(151): call_user_func(Array)
#10 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'collection', Array, '\n\t\t\t{{ partial:...', Array)
#11 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(579): call_user_func_array(Array, Array)
#12 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(173): Statamic\View\Antlers\Parser->parseCallbackTags('<section class=...', Array)
#13 /var/www/vendor/statamic/cms/src/View/Antlers/Parser.php(126): Statamic\View\Antlers\Parser->parse('<section class=...', Array)
#14 /var/www/vendor/statamic/cms/src/View/Antlers/Engine.php(88): Statamic\View\Antlers\Parser->parseView('/var/www/resour...', '<section class=...', Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get('/var/www/resour...', Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#17 /var/www/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#18 /var/www/vendor/statamic/cms/src/View/View.php(74): Illuminate\View\View->render()
#19 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(139): Statamic\View\View->render()
#20 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(44): Statamic\Http\Responses\DataResponse->contents()
#21 /var/www/vendor/statamic/cms/src/Entries/Entry.php(278): Statamic\Http\Responses\DataResponse->toResponse(Object(Illuminate\Http\Request))
#22 /var/www/vendor/statamic/cms/src/Structures/Page.php(281): Statamic\Entries\Entry->toResponse(Object(Illuminate\Http\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(734): Statamic\Structures\Page->toResponse(Object(Illuminate\Http\Request))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(177): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\VanityRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PermanentRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}
```

**Comment by jesseleite** [comment] 2020-04-27 21:23
Hey @sluther, I'm having trouble understand what's going on here.  There have also been a number of improvements to both statamic/cms and the migrator here since December.  I'm closing this issue for now, but feel free to re-open an issue if you're still having trouble with the migrator after trying the latest versions of everything.

**Closed by jesseleite** 2020-04-27 21:23 UTC
Labels: bug
