### ISSUE TITLE
How can I migrate helpers/Modifiers.php

### ISSUE THREAD

**Issue by joevallender** [statamic/migrator#69] opened 2020-09-24 03:11 UTC
I've just installed a fresh Statamic v3 and migrated my v2 site into it. 

The script ran without any errors but when I visit the site I get `Statamic\Modifiers\ModifierNotFoundException`

I noticed with a grep that no automatic action had been taken on the file at `site/helpers/Modifiers.php`

It's no big deal to copy/change/reimplement myself, but in the documentation at https://statamic.dev/modifiers the 'build your own' link doesn't go anywhere. And nothing is noted in https://statamic.dev/upgrade-guide

How are Modifiers handled in v3? Thanks!

**Comment by jesseleite** [comment] 2020-09-24 14:22
Yeah nothing has been done on that front yet (closing this as it's a duplicate of https://github.com/statamic/migrator/issues/26).

Anyway, check out https://statamic.dev/extending/modifiers#creating-a-modifier.  A little bit has changed, but not much. 
 I might use the `make:modifier` command to generate your modifier classes, then paste your logic into them 👍

**Closed by jesseleite** 2020-09-24 14:22 UTC

**Comment by joevallender** [comment] 2020-09-25 02:29
Thanks, I can confirm that all works. Used the command to create a new file in app/Modifiers and was able to paste the existing modifier function across, changing its previously unique name to the index() function of what is now unique files. Cheers!

**Comment by jesseleite** [comment] 2020-09-26 02:45
@joevallender glad to hear!
