### ISSUE TITLE
Ideas for improving Migrator

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/migrator#27] opened 2019-12-20 08:39 UTC
1. default layout in v2 should be renamed to layout.antlers.html in v3 (currently: default.antlers.html)

2. global variables defined in global.yaml should be automagically prepended by global: in the various antlers.html templates and layouts

3. paths to assets in content files should be sanitized regarding the new folder organization in v3 (i.e. /assets/my-image.jpg in v2 has to be corrected to my-image.jpg in v3)

**Comment by jasonvarga** [comment] 2019-12-20 13:20
Points 1 and 2 are unnecessary. Why do you need that to happen?

Point 3 is duplicate of #3

**Comment by ebeauchamps** [comment] 2019-12-20 13:27
Point 1: using MIGRATOR, the default layout is put in a layouts folder and is named default.antlers.html. views are looking for a layout.antlers.html file

Point 2: well, unnecessary...you have to look for all your global variables in your templates and layout files to add this as per the docs, so...could be easier I guess

**Comment by jesseleite** [comment] 2020-04-27 15:51
Fixed points 1 and 3 👌

Not sure what you mean by point 2 though.  The v2 template syntax for accessing globals is non-breaking in v3, so I think we should just leave this.

**Closed by jesseleite** 2020-04-27 15:51 UTC

**Comment by ebeauchamps** [comment] 2020-04-27 16:39
Hello @jesseleite 
When migrating, the references to my globals in my v3 templates just stayed as they were written in my v2 templates, but I remember having a discussion with Jason who asked me to prepend the globals with "global:". Perhaps should I try again to migrate the same site?

**Comment by jesseleite** [comment] 2020-04-27 17:12
The syntax from v2 is non-breaking in v3. You don't need to prepend `global:` to the default `global` set (but you can if you want).

For any other global set you would need to prepend though (eg. prepend `footer:` for vars in the `footer` global set).
